require 'rake'
require 'date'
require_relative 'config/application'
require_relative 'app/models/ingredient'

desc "create the database"
task "db:create" do
  puts "Creating file #{DB_PATH} if it doesn't exist..."
  touch DB_PATH
end

desc "drop the database"
task "db:drop" do
  puts "Deleting #{DB_PATH}..."
  rm_f DB_PATH
end

desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task "db:migrate" do
  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
  end
end

desc "populate the test database with sample data"
task "db:seed" do
  Ingredient.create(name: 'onion')
  Ingredient.create(name: 'apple')
  Ingredient.create(name: 'carrot')
  Ingredient.create(name: 'sugar')
  Ingredient.create(name: 'flour')
  Ingredient.create(name: 'egg')
  Ingredient.create(name: 'spinach')
  Ingredient.create(name: 'quinoa')
  Ingredient.create(name: 'curry')
  Ingredient.create(name: 'chicken')
  Ingredient.create(name: 'sour cream')
  Ingredient.create(name: 'black beans')
end

desc "add exp dates to ingredients"
task "db:add_dates" do
  Ingredient.all.each do |ingredient|
    date = Date.today + rand(15)
    ingredient.expiration_date = date
    ingredient.save
  end
end

desc 'Retrieves the current schema version number'
task "db:version" do
  puts "Current version: #{ActiveRecord::Migrator.current_version}"
end

desc 'Start IRB with application environment loaded'
task "console" do
  exec "irb -r./config/application"
end

